// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function ApplyColumnOperation(arg1:string,arg2:domain.ColumnOperation):Promise<domain.OperationResult>;

export function ApplyRowOperation(arg1:string,arg2:Record<string, any>):Promise<domain.OperationResult>;

export function CreateCsvFile(arg1:string,arg2:string,arg3:string):Promise<domain.CsvFileNode>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<domain.FolderNode>;

export function CreateProject(arg1:string,arg2:string):Promise<domain.ProjectNode>;

export function CreateRestorePoint(arg1:string,arg2:string,arg3:string):Promise<domain.RestorePoint>;

export function DeleteCsvFile(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteRestorePoint(arg1:string):Promise<void>;

export function GetDeviceMacAddress():Promise<string>;

export function GetFieldMetadata():Promise<Array<domain.KioFieldMetadata>>;

export function GetKioProject(arg1:string):Promise<domain.KioProject>;

export function GetProjectDirtySummary(arg1:string):Promise<domain.DirtySummary>;

export function GetVariableAllFields(arg1:string):Promise<Array<domain.KioFieldValue>>;

export function ListRestorePoints(arg1:string):Promise<Array<domain.RestorePoint>>;

export function LoadWorkspaceTree():Promise<domain.WorkspaceTree>;

export function PreviewColumnOperation(arg1:string,arg2:domain.ColumnOperation):Promise<domain.OperationPreview>;

export function PreviewRowOperation(arg1:string,arg2:Record<string, any>):Promise<domain.OperationPreview>;

export function RenameCsvFile(arg1:string,arg2:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string):Promise<void>;

export function RestoreProject(arg1:string,arg2:string):Promise<void>;

export function SaveImportedKioCsv(arg1:string,arg2:Array<string>,arg3:Array<domain.KioVariable>):Promise<domain.CsvFileNode>;

export function SaveKioExportFiles(arg1:Array<domain.KioExportFileRequest>):Promise<Array<domain.KioExportFileResult>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateCell(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateVariableFields(arg1:string,arg2:Record<string, string>):Promise<void>;
