// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyColumnOperation(arg1, arg2) {
  return window['go']['api']['AppAPI']['ApplyColumnOperation'](arg1, arg2);
}

export function ApplyRowOperation(arg1, arg2) {
  return window['go']['api']['AppAPI']['ApplyRowOperation'](arg1, arg2);
}

export function CreateCsvFile(arg1, arg2, arg3) {
  return window['go']['api']['AppAPI']['CreateCsvFile'](arg1, arg2, arg3);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['api']['AppAPI']['CreateFolder'](arg1, arg2, arg3);
}

export function CreateProject(arg1, arg2) {
  return window['go']['api']['AppAPI']['CreateProject'](arg1, arg2);
}

export function CreateRestorePoint(arg1, arg2, arg3) {
  return window['go']['api']['AppAPI']['CreateRestorePoint'](arg1, arg2, arg3);
}

export function DeleteCsvFile(arg1) {
  return window['go']['api']['AppAPI']['DeleteCsvFile'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['api']['AppAPI']['DeleteFolder'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['api']['AppAPI']['DeleteProject'](arg1);
}

export function DeleteRestorePoint(arg1) {
  return window['go']['api']['AppAPI']['DeleteRestorePoint'](arg1);
}

export function GetDeviceMacAddress() {
  return window['go']['api']['AppAPI']['GetDeviceMacAddress']();
}

export function GetFieldMetadata() {
  return window['go']['api']['AppAPI']['GetFieldMetadata']();
}

export function GetKioProject(arg1) {
  return window['go']['api']['AppAPI']['GetKioProject'](arg1);
}

export function GetProjectDirtySummary(arg1) {
  return window['go']['api']['AppAPI']['GetProjectDirtySummary'](arg1);
}

export function GetVariableAllFields(arg1) {
  return window['go']['api']['AppAPI']['GetVariableAllFields'](arg1);
}

export function ListRestorePoints(arg1) {
  return window['go']['api']['AppAPI']['ListRestorePoints'](arg1);
}

export function LoadWorkspaceTree() {
  return window['go']['api']['AppAPI']['LoadWorkspaceTree']();
}

export function PreviewColumnOperation(arg1, arg2) {
  return window['go']['api']['AppAPI']['PreviewColumnOperation'](arg1, arg2);
}

export function PreviewRowOperation(arg1, arg2) {
  return window['go']['api']['AppAPI']['PreviewRowOperation'](arg1, arg2);
}

export function RenameCsvFile(arg1, arg2) {
  return window['go']['api']['AppAPI']['RenameCsvFile'](arg1, arg2);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['api']['AppAPI']['RenameFolder'](arg1, arg2);
}

export function RenameProject(arg1, arg2) {
  return window['go']['api']['AppAPI']['RenameProject'](arg1, arg2);
}

export function RestoreProject(arg1, arg2) {
  return window['go']['api']['AppAPI']['RestoreProject'](arg1, arg2);
}

export function SaveImportedKioCsv(arg1, arg2, arg3) {
  return window['go']['api']['AppAPI']['SaveImportedKioCsv'](arg1, arg2, arg3);
}

export function SaveKioExportFiles(arg1) {
  return window['go']['api']['AppAPI']['SaveKioExportFiles'](arg1);
}

export function Startup(arg1) {
  return window['go']['api']['AppAPI']['Startup'](arg1);
}

export function UpdateCell(arg1, arg2, arg3) {
  return window['go']['api']['AppAPI']['UpdateCell'](arg1, arg2, arg3);
}

export function UpdateVariableFields(arg1, arg2) {
  return window['go']['api']['AppAPI']['UpdateVariableFields'](arg1, arg2);
}
